### ISSUE TITLE
Create share popup

### ISSUE THREAD

**Issue by awalmubarak** [ReDI-School/F24-Berlin-Web-Circle#117]
![Image](https://github.com/user-attachments/assets/b7f4fa24-0b85-431b-bdc8-7d992b82f346)

AC:
- Show this popup when the share icon on the product card component is clicked on
- The popup should look like the image above
- Show the name of the clicked product on the popup instead of a static text
- Don't focus on the actions for when the buttons on the popup is clicked. This will be done in another ticket

**Comment by xaved88** [comment]
The changes for this ticket are in https://github.com/ReDI-School/F24-Berlin-Web-Circle/issues/118
