### ISSUE TITLE
Create the json payload for all products

### ISSUE THREAD

**Issue by awalmubarak** [ReDI-School/F24-Berlin-Web-Circle#156]
We need to have a json file with a list products that'll be returned when the frontend calls the backend for products. This json file will server as the database for all products (for now).

AC:
- Create a new json file for all products
- Add a list of products. We should have at least 30 products in this list
- Each product should contain all the information on a product card
- Use dummy urls for the images for now

PS: you can use chatgpt to generate more products

**Comment by 006080** [comment]
Done
