### ISSUE TITLE
create the json payload for destinations search result

### ISSUE THREAD

**Issue by awalmubarak** [ReDI-School/F24-Berlin-Web-Circle#157]
We need to have a json file with a list of destinations that'll be returned when the frontend calls the backend for destinations. This json file will server as the database for all destinations (for now).

AC:

- Create a new json file for all destinations
- Add a list of destinations. We should have at least 20 destinations in this list
- Each destination should contain all the information on the destination result card
- Use dummy urls for the images for now

PS: you can use chatgpt to generate more destinations

**Comment by 006080** [comment]
Why should we create a new JSON file for the destination? It can be placed into one product.json file. Oder?

**Comment by Konzisam** [comment]
It turns out we have a map or destinations listing in some UIs. 
and since we have a map component we proceed with providing an endpoint which filters provides suggestions and filters based on the map clicks.

this end point is not needed in that case
