### ISSUE TITLE
Alow to filter by destination on places list endpoint

### ISSUE THREAD

**Issue by matus-vacula** [ReDI-School/F24-Berlin-Web-Circle#190]
AC:
- GET /places endpoint should allow to filter by destination

For instpiration the url can look like:

/places?destination=Madrid
/places?destinationId=200
/places/destination/Madrid/

**Comment by dvnishshanka** [comment]
For the above ticket I used a url same as in the airbnb eg:
https://www.airbnb.com/s/United-States/homes
