### ISSUE TITLE
Who and Where Popup should display when only related area click

### ISSUE THREAD

**Issue by matus-vacula** [ReDI-School/F24-Berlin-Web-Circle#203]
![Image](https://github.com/user-attachments/assets/aa094bb6-7f63-4596-aa3f-045be732d0b1)
Now who and where popup display statically it should display when related area click only
Input also updated in relevant field

AC:
- Destinations should popup only when "Where" is clicked
- The guest options should only appear whern "Who" is clicked

**Comment by orYoffe** [comment]
we removed the assignee, since there was no progress

**Comment by grabinskij** [comment]
I close this ticket because it is not actual anymore since ticket [#302](https://github.com/ReDI-School/F24-Berlin-Web-Circle/issues/302) and ticket
