### ISSUE TITLE
Prevent Overlapping Elements and Correct Z-Index

### ISSUE THREAD

**Issue by grabinskij** [ReDI-School/F24-Berlin-Web-Circle#253]
Resolve any instances of overlapping elements within the header and ensure the z-indexes of all elements are properly adjusted.
AC:
- resolve any instances of overlapping elements within the header;
- ensure the z-indexes of all elements are properly adjusted.

**Comment by 006080** [comment]
I’m not completely in agreement with the shadow implementation you used in the Header. I’ve opened a new ticket #266 to address this and will work on refining it. The shadow should be applied to the CategoriesTab component and should appear on the scroll, fixing itself at a specific point.

**Comment by grabinskij** [comment]
I am closing this ticket because a better solution has been found.

**Comment by grabinskij** [comment]
I reopened this ticket because I found additional issues that need to be improved
