### ISSUE TITLE
Favorite stay component

### ISSUE THREAD

**Issue by orYoffe** [ReDI-School/F24-Berlin-Web-Circle#27]
![Image](https://github.com/user-attachments/assets/3cc7f301-8846-44f4-af1c-e36862a71b61)
We should add the Favorite stay component from the product page.
Favorite stay should contain:
- Host Badge 
- Ratings score
- Review count
Example: https://www.airbnb.com/rooms/51257102

ACs:
- we have the Favorite stay component displaying in a page like the design from the airbnb website

**Comment by awalmubarak** [comment]
@Konzisam can you link the PR to this issue?

**Comment by Konzisam** [comment]
@awalmubarak I thought it's already linked.. Unless I missed something.
