### ISSUE TITLE
Finalize 1st version of the ERD

### ISSUE THREAD

**Issue by awalmubarak** [ReDI-School/F24-Berlin-Web-Circle#289]
We currently have an ERD for the backend. We need to finalize this by making sure it has all the properties from the current dummy json data.

Current version:
![Image](https://github.com/user-attachments/assets/0ed061b2-3a8b-49f5-97ac-f7c88cad599c)

AC:
- compare the ERD with the json data and add any missing fields
- discuss with the team if any new major changes are made
-  change Image_location name to a more descriptive name

**Comment by GabrielMelhem** [comment]
Here is the last ERD version 

![Image](https://github.com/user-attachments/assets/a72f51ab-a1bd-4dd9-8ac5-38d5d0cfb1ad)

**Comment by GabrielMelhem** [comment]
oh sorry here the final final one 

![Image](https://github.com/user-attachments/assets/c1580c33-37ff-40d6-a3ba-887f2aee01f6)
