### ISSUE TITLE
Fix SearchPanel test

### ISSUE THREAD

**Issue by orYoffe** [ReDI-School/F24-Berlin-Web-Circle#341]
currently, our `main` branch CI is broken because of the `src/components/SearchPanel/SearchPanel.test.jsx` test.
We should fix it so our CI is working and isn't blocking other PRs
https://github.com/ReDI-School/F24-Berlin-Web-Circle/actions/runs/12146267010/job/33869778645

AC:
- tests (CI) is passing in `main` branch

**Comment by grabinskij** [comment]
Fixed in the Fix bug with paraments in handleAirbnbSearch function #343
