### ISSUE TITLE
Host stats

### ISSUE THREAD

**Issue by orYoffe** [ReDI-School/F24-Berlin-Web-Circle#35]
We want to be able to add the host stats as a component to add to the product page later.
Or
As a user I want to see more clear stats about my host

Inside we should have:
- Host icon / avatar
- Host name
- Host status (superhost) & duration of hosting
- Self check-in option
- Host status full description (Raus is a Superhost)
- cancellation policy
![Image](https://github.com/user-attachments/assets/cc6cd6e2-ffaf-480d-b293-f79b922d2758)

ACs:
- We have the host stats as a component to add to the product page later, as seen on the site

**Comment by xaved88** [comment]
Closing this task as already done in others :)
