### ISSUE TITLE
Create categories carousel

### ISSUE THREAD

**Issue by awalmubarak** [ReDI-School/F24-Berlin-Web-Circle#39]
![Image](https://github.com/user-attachments/assets/6c31659c-1664-4dbb-8231-31863dbf6f50)

**Comment by messkalina** [comment]
Installed Airbnb icon package @airbnb/lunar-icons to project. I used  npm install @airbnb/lunar-icons --force because there was incompability with react versions. I created component using the icon library but cannor render the App.jsx as for now

**Comment by messkalina** [comment]
preview of the component
![Image](https://github.com/user-attachments/assets/2c498e20-c66f-4fce-a0a2-f0606c2e5d72)
![Image](https://github.com/user-attachments/assets/9b91d6bd-be04-4673-9bec-ced7717ef639)
