### ISSUE TITLE
Create product card

### ISSUE THREAD

**Issue by awalmubarak** [ReDI-School/F24-Berlin-Web-Circle#40]
As part of the basic components of the airbnb website we want to add the Product card item which shows in the homepage grid. 

![Image](https://github.com/user-attachments/assets/020dd256-3b5c-4844-97a1-cde30efc0cb2)

ACs:

- The card item should look like the image above

**Comment by messkalina** [comment]
![Image](https://github.com/user-attachments/assets/7edb2e35-5cb5-4239-9b8c-3fc3d895a8db)
