### ISSUE TITLE
[Meet the host] Overview card

### ISSUE THREAD

**Issue by orYoffe** [ReDI-School/F24-Berlin-Web-Circle#41]
![Image](https://github.com/user-attachments/assets/910ff648-71c2-46bc-b97f-0ad2d41754c1)
For the "Meet the host" section we want to be able to add the Overview card, shown above and here https://www.airbnb.com/rooms/1134757612770747812

with the host icon, name, status, reviews, ratings, and duration on platform

ACs:
- we can use the Overview card component to the meet the host section, but for now we'll add it in the homepage

**Comment by BajalanIman** [comment]
Also, should I push it as a new branch or in the same branch with a new commit?
