### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by matus-vacula** [ReDI-School/F24-Berlin-Web-Circle#69]
![Image](https://github.com/user-attachments/assets/c83d5708-f4aa-440b-bea5-091afed4c6c2)

AC:
- Calendar should show real dates for 2 months starting from current month
- We want to be able to go into future months (and come back) by clicking arrows. We don't want to go to the past months.
- We don't yet create the date range selection functionality

**Comment by awalmubarak** [comment]
@melikaamm can you link the PR to this issue?

**Comment by melikaamm** [comment]
> [@melikaamm](https://github.com/melikaamm) can you link the PR to this issue?

yes,i did

**Comment by grabinskij** [comment]
Since the newest PR Feature/embed calendar in reservation #259 with the newest changes was approved and merged to the main branch it is not need to approve or merge this PR. So, I close [Calendar](https://github.com/ReDI-School/F24-Berlin-Web-Circle/issues/69)
#69 ticket.
