### ISSUE TITLE
Create product highlights

### ISSUE THREAD

**Issue by awalmubarak** [ReDI-School/F24-Berlin-Web-Circle#86]
![Image](https://github.com/user-attachments/assets/c5856ae1-e600-46b8-a5da-098f2cb0710b)

ACs:
- It should look like the image above
- It should be a list of highlights instead of one giant component

**Comment by dvnishshanka** [comment]
![image](https://github.com/user-attachments/assets/83f3f8d4-4ce4-4c9b-ab2d-3b3e55e97ebb)
